version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    restart: always
    tty: true
    volumes:
      - ./backend/app:/app
